[package]
name = "gars"
version = "1.0.0"
authors = ["shane <shane@digitalsanctum.com>"]
edition = "2018"

[dependencies]
google-authenticator = "0.1.9"
clipboard = "0.5.0"
clipboard-ext = "0.2.0"
structopt = "0.3.13"
