[package]
name = "gars"
version = "0.0.3"
description = "Google Authenticator CLI."
authors = ["shane <shane@digitalsanctum.com>"]
edition = "2018"
license = "MIT"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
google-authenticator = "0.1.9"
